language: objective-c

xcode_workspace: Phoenix.xcworkspace
xcode_scheme: Phoenix

xcode_sdk: macosx10.14

notifications:
  email: false

before_install:
  - gem install xcpretty
  - npm install -g grunt-cli
  - npm install

matrix:
  include:
    - osx_image: xcode10.1
    - osx_image: xcode10
